apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: robotShop
description: main application pipeline
serialPipeline:
 stages:
 - targetId: 
   profiles: []
 - targetId: 
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: robot-shop-cluster
description: test cluster
gke:
 cluster: gcloud container clusters get-credentials robot-shop-cluster --zone us-central1-c --project thedevproj
